### ISSUE TITLE
Heroku deployment question

### ISSUE THREAD

**Issue by bborn** [ankane/trove#3]
Hi - I'm using the NER and sentiment analysis models, and together they push me over the Heroku slug limit. I tried taking `Trove.pull` out of my Rakefile and instead putting in an initializer, but it looks like the initializers gets loaded during complication, and the deploy fails.

Any tips on how to get around this?

**Comment by ankane** [comment]
Hey @bborn, you could try something like:

```ruby
Trove.pull unless ENV["BUILDPACK_LOG_FILE"]
```

in the initializer to pull when the app boots but not during the build step.

**Comment by ankane** [comment]
It's probably good to rescue any errors, so the app will still boot if S3 is down. To handle that situation gracefully, you could also call `Trove.pull(filename)` in the code where the model is needed, so it'll keep trying to pull the file if it doesn't exist until S3 is back up.

**Comment by bborn** [comment]
Thanks for the help. This worked for getting the models to load.
