### ISSUE TITLE
Cannot pull

### ISSUE THREAD

**Issue by bolshakov** [ankane/trove#4]
1. I push the model
```sh
$ bundle exec trove push lid.176.ftz
Already up-to-date
```
2. I remove the model:
```sh
rm trove/lid.176.ftz
```
3. I pull the model:

```sh
$ bundle exec trove pull lid.176.ftz
File not found
```

**Expected result**: the model appears as the `trove/lid.176.ftz`
**Actual result**: I see the `File not found` error. 

The model was indeed pushed to AWS:

```
$ bundle exec trove list
FILENAME           SIZE      UPDATED
lid.176.ftz        916KB     5 days ago
```

**Comment by ankane** [comment]
Hi @bolshakov, I'd check that your IAM user has [correct permissions](https://github.com/ankane/trove#amazon-s3) for the S3 bucket.

**Comment by ankane** [comment]
Just pushed a better error message. fwiw, I'm able to reproduce by removing the `s3:GetObjectVersion` permission. You can also get the full error message with:

```sh
DEBUG=t bundle exec trove pull lid.176.ftz
```
