### ISSUE TITLE
Loading model on initialization

### ISSUE THREAD

**Issue by dchun** [ankane/trove#6]
Hey thanks for the gem. Really useful.

Just curious if you had a need to pre load the model and keep it in memory so that you don't have to re-read the model file every time you want to parse some text since there is a decent delay of a second or two.

I tried loading the model in a constant in a rakefile after fetching the file from aws like you documented but it's not accessible in the app afterwards. And I can't load the model on initialization since the file is not present until after the precompilation step

**Comment by ankane** [comment]
Hi @dchun, I think loading the model just once typically ideal. You could check if the file exists before setting the constant (or an environment variable specific to the build is not set).

```ruby
MODEL = Model.load("trove/model.bin") if File.exist?("trove/model.bin")
```

Another approach would be to use memoization, so the model is only loaded when it's needed in development, with code to eager-load it in production.

**Comment by dchun** [comment]
@ankane I ended up adding the model to a constant in a module and eager loaded it. Thanks for your help!
